Interactive container
adobecom/cc pull request #105
Opened 2023-11-10 07:25 UTC by drashti1712

* Implemented the base Interactive Marquee container for the upcoming variant - Genfill and Firefly
* Figma: https://www.figma.com/file/L1YpIBovlcXffNVvOePgA9/Interactive-Marquee-KR?type=design&node-id=56-1516&mode=design&t=URlCADx9xEuFjjuk-0

Resolves: [MWPW-137345](https://jira.corp.adobe.com/browse/MWPW-137345)

**Test URLs:**
- Before: https://main--cc--adobecom.hlx.page/drafts/drashti/MWPW-137345/container/?martech=off
- After: https://interactive-container--cc--drashti1712.hlx.page/drafts/drashti/MWPW-137345/container/?martech=off

2023-11-10 10:25 UTC, suhjainadobe reviewed
Could you make css changes specificifically for your block only as it will affect other interactive blocks as well.

2023-11-14 18:25 UTC, Ruchika4 requested changes

2023-11-14 18:25 UTC, Ruchika4 commented on creativecloud/blocks/interactive-marquee/interactive-marquee.js
> +      const video = child.querySelector('video, a[href*=".mp4"]');
I think we can remove this line of code as we only need images to be decorated

2023-11-14 18:25 UTC, Ruchika4 commented on creativecloud/blocks/interactive-marquee/interactive-marquee.js
> +      if (image && !video) {
I believe we can just have a check for if(image) here

2023-11-15 07:47 UTC, aishwaryamathuria approved these changes

2023-11-17 11:27 UTC, salonijain3 commented
@drashti1712 you can raise these changes with the main branch - interactive for genfill variant

2023-11-17 11:27 UTC, closed without merging