Change bg marquee
adobecom/cc pull request #108
Opened 2023-11-14 17:35 UTC by suhjainadobe

* Add your specific features or fixes

Resolves: [MWPW-NUMBER](https://jira.corp.adobe.com/browse/MWPW-NUMBER)

**Test URLs:**
- Before: https://main--cc--adobecom.hlx.page/?martech=off
- After: https://change-bg-marquee--cc--suhjainadobe.hlx.page/drafts/suhjain/imarquee#

2023-11-15 05:30 UTC, aishwaryamathuria commented
@suhjainadobe The unit tests are failing. Could you take a look?

2023-11-15 06:11 UTC, suhjainadobe commented
Unit Test cases:
<img width="1454" alt="image" src="https://github.com/adobecom/cc/assets/110388864/76acd904-d1ea-4bc6-bb26-ef12d08ba9f6">

2023-11-15 07:18 UTC, aishwaryamathuria commented
> Unit Test cases: <img alt="image" width="1454" src="https://user-images.githubusercontent.com/110388864/283020507-76acd904-d1ea-4bc6-bb26-ef12d08ba9f6.png">

You can add the following ignore pattern for the library files in `.eslintrc.js` as they will continue to throw lint errors and should not be validated by the linter
```
  ignorePatterns: [
    '/creativecloud/deps/*',
  ],
```

2023-11-15 07:19 UTC, aishwaryamathuria commented on creativecloud/blocks/interactive-marquee/interactive-marquee.css
> +
YOu can add a comment in this file as it would throw lint error if it is empty

2023-11-15 07:22 UTC, aishwaryamathuria commented on creativecloud/scripts/scripts.js
> +    firstDiv.querySelector(':scope > div:nth-child(1)').querySelectorAll('img').forEach(eagerLoad);
Move this check to be executed before library import to avoid any failures due to race condition

2023-11-15 07:25 UTC, aishwaryamathuria commented on creativecloud/scripts/scripts.js
> +    firstDiv.querySelector(':scope > div:nth-child(1)').querySelectorAll('img').forEach(eagerLoad);
nit: Lets move this one line above just to avoid race condition.

2023-11-15 07:26 UTC, aishwaryamathuria commented on creativecloud/features/changeBg/changeBg.js
> +export default async function changeBg(el) {
We can remove async from this feature function.

2023-11-15 07:30 UTC, aishwaryamathuria commented on test/blocks/changeBg/changeBg.test.js
> +import sinon, { stub } from 'sinon';
If this is not used it can be removed

2023-11-15 07:31 UTC, aishwaryamathuria commented on creativecloud/blocks/interactive-marquee/interactive-marquee.css
> +
You can add a comment in this file as it would throw lint error if it is empty

2023-11-15 07:31 UTC, aishwaryamathuria requested changes

2023-11-15 07:31 UTC, aishwaryamathuria commented on creativecloud/blocks/interactive-marquee/interactive-marquee.css
> +
You can add a comment in this file as it would throw lint error if it is empty

2023-11-15 09:08 UTC, aishwaryamathuria approved these changes

2023-11-16 16:26 UTC, salonijain3 approved these changes

2023-11-17 07:20 UTC, merged