MWPW-137345 | [For Stage] Interactive container block for CC only
adobecom/cc pull request #109
Opened 2023-11-15 08:04 UTC by drashti1712

* Implemented the base Interactive Marquee container for the upcoming variant - Genfill and Firefly
* Figma: https://www.figma.com/file/L1YpIBovlcXffNVvOePgA9/Interactive-Marquee-KR?type=design&node-id=56-1516&mode=design&t=URlCADx9xEuFjjuk-0

Resolves: [MWPW-138595](https://jira.corp.adobe.com/browse/MWPW-138595)

**Test URLs:**
- Before: https://main--cc--adobecom.hlx.page/drafts/drashti/MWPW-137345/container/?martech=off
- After: https://interactive-container--cc--drashti1712.hlx.page/drafts/drashti/MWPW-137345/container/?martech=off

2023-11-15 08:16 UTC, aishwaryamathuria approved these changes

2023-11-15 09:11 UTC, salonijain3 approved these changes

2023-11-15 09:11 UTC, salonijain3 commented on creativecloud/blocks/interactive-marquee/interactive-marquee.js
> +// [headingSize, bodySize, detailSize, titlesize]
remove comments

2023-11-15 10:39 UTC, suhjainadobe commented
The init function can be changed afterwards once https://github.com/adobecom/cc/pull/108/files to incorporate switch case.

2023-11-15 10:40 UTC, suhjainadobe approved these changes

2023-11-15 18:15 UTC, Ruchika4 requested changes

2023-11-15 18:15 UTC, Ruchika4 commented on creativecloud/blocks/interactive-marquee/interactive-marquee.js
> +function interactiveInit(el) {
can we make this function async? I have an await call to add in this function to load firefly js file.

2023-11-15 20:14 UTC, Ruchika4 approved these changes

2023-11-16 00:21 UTC, Ruchika4 commented
Merging this PR to raise the PR for firefly marquee

2023-11-16 00:21 UTC, merged