[MWPW-140096] Genfill Marquee images are blinking during auto play and on click as well in Firefox browser
adobecom/cc pull request #144
Opened 2023-12-12 10:01 UTC by drashti1712

* Bug fix - Image flickering issue on firefox browser (Genfill)

Resolves: [MWPW-140096](https://jira.corp.adobe.com/browse/MWPW-140096)

**Test URLs:**
- Before: https://main--cc--adobecom.hlx.live/drafts/drashti/MWPW-137345/genfill-container?martech=off
- After: https://genfill-flicker--cc--drashti1712.hlx.live/drafts/drashti/MWPW-137345/genfill-container?martech=off

2023-12-12 12:49 UTC, aishwaryamathuria approved these changes

2023-12-12 12:52 UTC, aishwaryamathuria requested changes

2023-12-12 12:52 UTC, aishwaryamathuria commented on creativecloud/features/genfill/genfill-interactive.js
> +  img.alt = deviceConfig[viewport].altList[nextIndex];
Image alt ahould be same as the image and not the daa-ll

2023-12-12 12:52 UTC, aishwaryamathuria commented on creativecloud/features/genfill/genfill-interactive.js
> +  [img.alt] = [deviceConfig[viewport].altList];
Image alt ahould be same as the image and not the daa-ll

2023-12-13 05:06 UTC, aishwaryamathuria commented on creativecloud/features/genfill/genfill-interactive.js
> +  const alt = deviceConfig[v].altList[nextIndex];
```suggestion
  const alt = deviceConfig[v].altList[nextIndex];
  if (alt) img.alt = alt
```

2023-12-13 05:08 UTC, aishwaryamathuria commented on creativecloud/features/genfill/genfill-interactive.js
> +  const alt = deviceConfig[v].altList[nextIndex];
```suggestion
  const alt = deviceConfig[v].altList[nextIndex];
  if (alt) img.alt = alt;
```

2023-12-13 05:09 UTC, aishwaryamathuria commented on creativecloud/features/genfill/genfill-interactive.js
> +  [img.alt] = generateDaaLL(hText, alt, v);
Alt should not be modified value.. daa-ll should be in a tag only.
if (alt) img.alt = alt

2023-12-13 05:10 UTC, aishwaryamathuria commented on creativecloud/features/genfill/genfill-interactive.js
> +  [img.alt] = generateDaaLL(hText, alt, v);
```suggestion
  if (alt) img.alt = alt;
```

2023-12-13 06:26 UTC, aishwaryamathuria approved these changes

2023-12-13 08:12 UTC, Anupamasonnalagi commented
Verified the issue. It's fine now.
https://genfill-flicker--cc--drashti1712.hlx.page/creativecloud/animation/discover/testdraftsfirefly/genfill/psgenfill

2023-12-13 14:48 UTC, salonijain3 approved these changes

2023-12-14 06:08 UTC, merged