[MWPW-147521] interactive marquee container is not seen displayed as expected with resize flow
adobecom/cc pull request #301
Opened 2024-05-16 12:40 UTC by drashti1712

* Fixes the foreground container width of the interactive marquee so that the text does not touch the edge of the screen on lower desktop screen sizes
* Also fixes the generate prompt for firefly interactive marquee, which was going out of the image for screen size > 1200px and < 1300px.

Resolves: [MWPW-147521](https://jira.corp.adobe.com/browse/MWPW-147521)

**Test URLs:**
- Before: https://main--cc--adobecom.hlx.live/docs/library/kitchen-sink/interactive-marquee?martech=off
- After: https://int-fix--cc--drashti1712.hlx.page/docs/library/kitchen-sink/interactive-marquee?martech=off

2024-05-16 12:57 UTC, aishwaryamathuria requested changes
@drashti1712 The fix is breaking the enticement arrow

<img width="1108" alt="Screenshot 2024-05-16 at 6 27 10 PM" src="https://github.com/adobecom/cc/assets/9293441/c7461903-b266-447e-93a9-48dd1f35429b">

And also adding some additional issue in the link

<img width="95" alt="Screenshot 2024-05-16 at 6 27 19 PM" src="https://github.com/adobecom/cc/assets/9293441/17f285eb-2697-4b54-91a6-edae669910ed">

2024-05-17 06:01 UTC, aishwaryamathuria approved these changes

2024-05-17 06:51 UTC, salonijain3 approved these changes

2024-05-17 08:17 UTC, spadmasa commented
Verified the flow after the fix :in different browsers and devices.
https://int-fix--cc--drashti1712.hlx.live/drafts/drashti/bugs/interactive-marquee?martech=off
![image](https://github.com/adobecom/cc/assets/73129464/6c4574ef-9496-4964-b581-812821a3da60)

![image](https://github.com/adobecom/cc/assets/73129464/b4207203-87ce-4c4f-b2f0-c751e89dc498)

![image](https://github.com/adobecom/cc/assets/73129464/526bb421-52d0-4f07-8777-0a1f21e8b6b4)

2024-05-20 06:09 UTC, merged