https://jira.corp.adobe.com/browse/MWPW-148229 -Milo Catalog Batch00d - Left Rail filter hover Text
adobecom/cc pull request #360
Opened 2024-07-23 06:43 UTC by adgaurgit

https://jira.corp.adobe.com/browse/MWPW-148229 -Milo Catalog Batch00d - Left Rail filter hover Text

![image](https://github.com/user-attachments/assets/fe3b29df-f83a-4b16-9f42-33ca14c87042)

Test URLs:

Before: https://main--cc--adobecom.hlx.live/products/catalog
After: https://mwpw-148229--cc--adobecom.hlx.live/products/catalog

2024-07-23 13:23 UTC, mirafedas approved these changes

2024-07-23 13:49 UTC, rahulgupta999 approved these changes

2024-07-24 09:14 UTC, npeltier requested changes

2024-07-24 09:14 UTC, npeltier commented on creativecloud/deps/merch-sidenav.js
> -// branch: main commit: d113c9c27640ef88ab28eff3ef4637919479e540 Wed, 03 Jul 2024 15:04:49 GMT
@adgaurgit please update this dependency with latest main build (with that header).
you'll find it from running `npm run build:milo` and picking dep from milo-libs folder in mas project

2024-07-25 10:32 UTC, npeltier approved these changes

2024-07-25 12:14 UTC, aishwaryamathuria approved these changes

2024-07-25 12:15 UTC, merged