MWPW-153245 [catalog] analytics fixes
adobecom/cc pull request #364
Opened 2024-07-24 17:35 UTC by npeltier

- listen to newly created WC events and call analytics API directly (see https://github.com/orgs/adobecom/discussions/2512),
- only consume one (minified) sidenav dependency,
- decorate catalog instead of collection (less levels),
- decorate card name at the link level, to prevent having card information at the end of the event,
Resolves: [MWPW-136881](https://jira.corp.adobe.com/browse/MWPW-136881)
milo PR: https://github.com/adobecom/milo/pull/2610
mas PR: https://github.com/adobecom/mas/pull/42
**Test URLs:**
- Before: https://main--cc--adobecom.hlx.live/?martech=off
- After: https://<branch>--cc--adobecom.hlx.live/?martech=off

- Before: https://main--cc--adobecom.hlx.live/products/catalog?milolibs=mwpw-153245--milo--npeltier
- After: https://mwpw-153245--cc--npeltier.hlx.live/products/catalog?milolibs=mwpw-153245--milo--npeltier

2024-07-25 10:49 UTC, mirafedas commented on creativecloud/blocks/catalog/catalog.js
> +  merchCards.querySelectorAll('merch-card').forEach(async (card) => {
Is `async` needed here?

2024-07-25 10:52 UTC, mirafedas requested changes

2024-07-25 10:52 UTC, mirafedas commented on creativecloud/blocks/catalog/catalog.js
> +function handleCustomAnalyticsEvent(eventName, element) {
Should we maybe add some tests for `handleCustomAnalyticsEvent` and `enableAnalytics`?

2024-07-25 19:12 UTC, npeltier commented
@mirafedas 
<img width="1025" alt="image" src="https://github.com/user-attachments/assets/fefff37d-bef0-4e70-b792-80dd6dc24a7a">

2024-07-26 10:04 UTC, mirafedas approved these changes

2024-07-26 12:34 UTC, 3ch023 approved these changes

2024-07-26 15:30 UTC, Axelcureno approved these changes

2024-07-29 08:43 UTC, aishwaryamathuria commented
@npeltier @mirafedas @3ch023 Could you confirm if PR is verified by adding the 'verified' label?

2024-07-29 09:52 UTC, Roycethan commented
> @npeltier @mirafedas @3ch023 Could you confirm if PR is verified by adding the 'verified' label?

Done added label , although in Milo process we will give importance to Ready for stage label, if its there that means its verified. Thanks

2024-07-30 10:26 UTC, aishwaryamathuria approved these changes

2024-07-30 12:28 UTC, merged