Mwpw155686preview2
adobecom/cc pull request #391
Opened 2024-08-14 12:01 UTC by bozojovicic

With PR [#389](https://github.com/adobecom/cc/pull/389) we confirmed that the event `resource-previewed` works in GitHub actions on main repo. The handler for this event is provided now. For the resource path that we get in that event we will 

- read the resource details
- update preview index with these details or
- insert the new row with them.

Again, this change cannot be tested on fork. PR needs to be merged and then tested on main repo.

Resolves: [MWPW-155686](https://jira.corp.adobe.com/browse/MWPW-155686)

**Test URLs:**
- Before: https://main--cc--adobecom.hlx.live/?martech=off
- After: https://mwpw155686preview2--cc--bozojovicic.hlx.live/?martech=off

2024-08-16 10:55 UTC, 3ch023 requested changes
A lot of single.js contents seem to copy the update.js,
could you refactor it the way that methods validateConfig, getAccessToken etc are only defined once?
maybe create a sharepoint.js file to consume in both?
example: https://git.corp.adobe.com/jsingler/sp-auth 

please also add a note in readme explaining the difference between update.js and single.js
also maybe we want to rename them somewhat better.. indexSingle.js & indexFull.js?

2024-08-19 12:11 UTC, 3ch023 approved these changes
looks great!

2024-08-19 12:16 UTC, mirafedas approved these changes

2024-08-19 15:27 UTC, aishwaryamathuria approved these changes

2024-08-19 15:28 UTC, merged