Checkmark cta
adobecom/cc pull request #42
Opened 2023-04-27 22:27 UTC by So1ene

* A `checkmark-cta` block for the Substance3D team to use in their Plugin Pages (example of an old page that will soon be migrated to this franklin website: https://substance3d.adobe.com/plugins/substance-in-3ds-max/)
* The checkbox should enable the CTA when checked, and disable it when unchecked.

**Test URLs:**
- Before: https://main--cc--adobecom.hlx.page/drafts/solene/checkmark-cta/checkmark-cta?martech=off
- After: https://checkmark-cta--cc--wbstry.hlx.page/drafts/solene/checkmark-cta/checkmark-cta?martech=off

2023-04-28 02:10 UTC, Ruchika4 requested changes

2023-04-28 02:10 UTC, Ruchika4 commented on creativecloud/scripts/scripts.js
I have updated the utils.js to fix the issue here getLibs was returning undefined in this PR https://github.com/orgs/adobecom/discussions/672 As it already has export the I think we can use that to get the libs. Once the above PR merged we can use below code in checkmark-cta and will not need to update scripts.js
<img width="992" alt="Screen Shot 2023-04-27 at 7 04 56 PM" src="https://user-images.githubusercontent.com/69535463/235037397-6d57261f-306d-44e8-977e-f036edac4c9a.png">
.js

2023-04-28 02:18 UTC, Ruchika4 commented
@So1ene , could you please add the jira ticket also to the PR description

2023-05-03 18:36 UTC, Ruchika4 commented
@So1ene Please add jira ticket to the pr description.

2023-05-19 16:15 UTC, Ruchika4 commented
> Sorry here you go! https://jira.corp.adobe.com/browse/MWPW-130573

Thanks for sharing the jira ticket. I am not able to see a xd design for this block. Could you please share that too.

2023-05-19 16:19 UTC, aishwaryamathuria commented
@So1ene 
Could you please confirm the use case for this block? Are there any substance3d pages currently migrated that need this block and was this created as a part of the same requirement?
Could we get a review on this from someone on substance team or Milo team who are aware of the the detailed use case?

2023-05-19 16:20 UTC, Ruchika4 requested changes

2023-05-19 16:20 UTC, Ruchika4 commented on creativecloud/blocks/checkmark-cta/checkmark-cta.js
> +const checkmarkCTA = (block) => {
Can we please have this function name as init to follow the milo nomenclature for blocks?

2023-06-19 15:57 UTC, Ruchika4 commented
Closing this PR as requested by @williambsm

2023-06-19 15:57 UTC, closed without merging