MWPW-160516: Nonprofits Email validation
adobecom/cc pull request #440
Opened 2024-10-29 16:16 UTC by joaquinrivero

- Email input validation

Resolves: [MWPW-160516](https://jira.corp.adobe.com/browse/MWPW-160516)

**Test URLs:**

- Before: https://main--cc--adobecom.hlx.page/drafts/rivero/nonprofits?martech=off  
- After: https://mwpw-160516--cc--adobecom.hlx.page/drafts/rivero/nonprofits?martech=off

2024-10-30 15:22 UTC, tedAir requested changes
<img width="1067" alt="NonProfit-WrongEmail-NoError" src="https://github.com/user-attachments/assets/ddeb3edc-f4d2-48ba-85ce-ccfbbe74000e">

There is no Error mark.

2024-11-04 20:34 UTC, TsayAdobe approved these changes

2024-11-04 22:46 UTC, tedAir approved these changes
There is a minor issue that when user enters a saved wrong email address, there is no check on it automatically. Will file a different ticket to track this minor issue.

2024-11-05 05:14 UTC, aishwaryamathuria approved these changes

2024-11-05 05:14 UTC, aishwaryamathuria approved these changes

2024-11-05 05:21 UTC, merged