MWPW-157433 Preload LCP resources on Catalog Page
adobecom/cc pull request #444
Opened 2024-11-06 15:30 UTC by bozojovicic

What @mokimo  started in https://github.com/adobecom/milo/pull/2914 
and @spadmasa continued in https://github.com/adobecom/cc/pull/433
now I will try to finish for Catalog page.
Soujanya already added preloading of utils.js
On top of her code I added preloading of these resources

- /libs/blocks/text/text.js
- /libs/blocks/text/text.css
- /libs/blocks/mnemonic-list/mnemonic-list.css

which are reported as critical for LCP.

<img width="922" alt="Screenshot 2024-11-06 at 16 27 33" src="https://github.com/user-attachments/assets/c30bdfbf-e999-4d80-a0da-7fcd7499eca5">

Test URL https://mwpw157433lcp--cc--bozojovicic.hlx.page/products/catalog?martech=off

Resolves: [MWPW-157433](https://jira.corp.adobe.com/browse/MWPW-157433)

**Test URLs:**
- Before: https://main--cc--adobecom.hlx.live/?martech=off
- After: https://mwpw157433lcp--cc--bozojovicic.hlx.live/?martech=off

2024-11-06 16:27 UTC, yesil requested changes
the Milo feature works on CC OOTB afaik, I'm not sure a CC version is needed.
Also, in this script we should not add any page specific script.

![image](https://github.com/user-attachments/assets/69e697a0-f4d7-4972-a022-ffe813783764)

2024-11-06 16:55 UTC, bozojovicic commented
@yesil I talked with Okan last week and I understood him that in his PR he just provided a good example/mechanism how to preload some resources. Soujanya preloaded utils.js in that way so I just added 
`['${miloLibs}/blocks/text/text.js', '${miloLibs}/blocks/text/text.css', '${miloLibs}/blocks/mnemonic-list/mnemonic-list.css'];`
to her list of paths that should be preloaded, but indeed all of these are already loaded before LCP.

So after all their work, we can actually close this PR and MWPW-157433, do you agree?

2024-11-08 01:41 UTC, Axelcureno approved these changes

2024-11-08 08:19 UTC, yesil commented
@bozojovicic I think as per https://github.com/adobecom/milo/pull/2914/files#diff-28218f239d8d9c4d41e1924854440b50964619e56058fdd0ae243ff5ff6c616dR1232, the blocks in the first section are preloaded by Milo, therefore I would close this PR.

2024-11-08 12:02 UTC, bozojovicic commented
Closing then ...

2024-11-08 12:02 UTC, closed without merging