Version History tools
adobecom/cc pull request #85
Opened 2023-09-07 05:24 UTC by bandana147

* Adds Version history button under tools

Resolves: [MWPW-130163](https://jira.corp.adobe.com/browse/MWPW-130163)

**Test URLs**
* [CC Test URL](https://version-history--milo--adobecom.hlx.page/tools/version-history?repo=cc&owner=adobecom&referrer=https%3A%2F%2Fadobe.sharepoint.com%2F%3Aw%3A%2Fr%2Fsites%2Fadobecom%2F_layouts%2F15%2FDoc.aspx%3Fsourcedoc%3D%257B03F85933-003D-4B6D-9786-8252E5052F08%257D%26file%3Ddemo.docx)

2023-09-11 05:14 UTC, salonijain3 approved these changes

2023-09-11 14:55 UTC, Ruchika4 requested changes

2023-09-11 14:55 UTC, Ruchika4 commented on tools/sidekick/config.json
>      }
I believe we added support for xlsx files too in version history. Can you please add .xlsx also in includePaths?

2023-09-12 04:43 UTC, bandana147 commented
Already added so closing this.

2023-09-12 04:43 UTC, closed without merging